# Generated by Django 5.2 on 2025-05-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='topic',
            field=models.JSONField(default=[]),
        ),
    ]
