# Generated by Django 5.2 on 2025-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0002_alter_generatedcontent_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='objetives',
            field=models.JSONField(default=[]),
        ),
    ]
