# Generated by Django 5.2 on 2025-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0003_generatedcontent_objetives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='objetives',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='topic',
            field=models.JSONField(default=list),
        ),
    ]
