# Generated by Django 5.2 on 2025-06-08 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0004_alter_generatedcontent_objetives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='objetives',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='topic',
        ),
        migrations.CreateModel(
            name='AnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_title', models.CharField(max_length=255)),
                ('unit_objectives', models.JSONField(default=list)),
                ('unit_contents', models.JSONField(default=list)),
                ('methodologies', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='annualplan_pdf/')),
                ('evaluation_criteria', models.JSONField(default=list)),
                ('evaluation_indicators', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_annualplans', to='educamy.generatedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='MicroPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetives', models.JSONField(default=list)),
                ('topic', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='microplan_pdf/')),
                ('generated_content', models.TextField()),
                ('year', models.PositiveIntegerField(default=2025)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educamy.schoolsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='questions_pdf/')),
                ('answer_choices', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='educamy.generatedcontent')),
            ],
        ),
    ]
