# Generated by Django 5.2 on 2025-06-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0005_remove_generatedcontent_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anualplan",
            name="generated_content",
        ),
        migrations.AddField(
            model_name="anualplan",
            name="generatedContentId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_annualplans",
                to="educamy.generatedcontent",
            ),
        ),
        migrations.AddField(
            model_name="microplan",
            name="generatedContentId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_microplans",
                to="educamy.generatedcontent",
            ),
        ),
        migrations.AddField(
            model_name="questions",
            name="generatedContentId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_questions",
                to="educamy.generatedcontent",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="generated_content",
            field=models.TextField(),
        ),
    ]
