# Generated by Django 5.2 on 2025-06-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0006_remove_anualplan_generated_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anualplan",
            name="school_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="educamy.schoolsubject",
            ),
        ),
        migrations.AlterField(
            model_name="microplan",
            name="school_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="educamy.schoolsubject",
            ),
        ),
    ]
