# Generated by Django 5.2 on 2025-06-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0007_anualplan_school_subject_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anualplan",
            old_name="unit_objectives",
            new_name="goals",
        ),
        migrations.RenameField(
            model_name="microplan",
            old_name="objetives",
            new_name="goals",
        ),
    ]
