# Generated by Django 5.2 on 2025-06-09 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0008_rename_unit_objectives_anualplan_goals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anualplan",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="anualplan",
            name="grade",
            field=models.CharField(default="Primero", max_length=200),
        ),
        migrations.AddField(
            model_name="anualplan",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="anualplan",
            name="year",
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
