# Generated by Django 5.2 on 2025-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0009_anualplan_end_date_anualplan_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anualplan",
            name="unit_title",
            field=models.JSONField(default=list),
        ),
    ]
