# Generated by Django 5.2 on 2025-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0010_alter_anualplan_unit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='microplan',
            name='unit_title',
            field=models.JSONField(default=list),
        ),
    ]
