# Generated by Django 5.2 on 2025-06-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0012_microplan_evaluation_criteria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PptxFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pptxfile",
                    models.FileField(blank=True, null=True, upload_to="pptx_files/"),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anual_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pptx_files",
                        to="educamy.anualplan",
                    ),
                ),
                (
                    "micro_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pptx_files",
                        to="educamy.microplan",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
    ]
