# Generated by Django 5.2 on 2025-06-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0013_pptxfile_delete_questions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
