# Generated by Django 5.2 on 2025-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0014_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="anualplan",
            name="college_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="anualplan",
            name="teacher_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="microplan",
            name="college_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="microplan",
            name="teacher_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
