# Generated by Django 5.2 on 2025-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0016_anualplan_area_microplan_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="anualplan",
            name="transversal_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="microplan",
            name="transversal_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
