# Generated by Django 5.2 on 2025-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0017_anualplan_transversal_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anualplan",
            name="parallel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="microplan",
            name="parallel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
