# Generated by Django 5.2 on 2025-06-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0018_anualplan_parallel_microplan_parallel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anualplan",
            name="transversal_value",
        ),
        migrations.RemoveField(
            model_name="microplan",
            name="transversal_value",
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_index", models.PositiveIntegerField()),
                ("topic_index", models.PositiveIntegerField()),
                ("question_text", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="quiz_pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anual_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_anual",
                        to="educamy.anualplan",
                    ),
                ),
                (
                    "microplan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_micro",
                        to="educamy.microplan",
                    ),
                ),
            ],
            options={
                "ordering": ["microplan", "unit_index", "topic_index"],
            },
        ),
    ]
