# Generated by Django 5.2 on 2025-06-29 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0019_remove_anualplan_transversal_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content_topic", models.TextField()),
                ("unit_number", models.IntegerField()),
                ("quiz_data", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="quizzes/"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("completed", "Completado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "anual_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_anual",
                        to="educamy.anualplan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microplan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_micro",
                        to="educamy.microplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_date"],
            },
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
