# Generated by Django 5.2 on 2025-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0021_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
