# Generated by Django 5.2 on 2025-07-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0022_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsubject",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="school_subject_files/"
            ),
        ),
    ]
