# Generated by Django 5.2 on 2025-07-04 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0023_schoolsubject_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptxfile",
            name="file_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="pptxfile",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
