# Generated by Django 5.2 on 2025-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0024_pptxfile_file_url_alter_pptxfile_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptxfile",
            name="unit_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
