# Generated by Django 5.2 on 2025-07-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educamy", "0025_pptxfile_unit_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
